version: '3'
services:

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root2023toor
    volumes:
      - "./script.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "3306:3306"
  
  javams:
    build:
      context: .
      dockerfile: Dockerfile-java
    depends_on:
      - db
    ports:
      - "8080:8080"
      
      
  vuejs-app:
    build:
      context: .
      dockerfile: Dockerfile-vue
    container_name: vuejs-app
    working_dir: /app
    volumes:
      - ./vue:/app
      - /app/node_modules
    ports:
      - "8081:8080"
    command: npm run serve
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
      

      
      
      
  

  
