version: '3'
services:

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root2023toor
    volumes:
      - "./script.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "3306:3306"
  
  javams:
    build:
      context: .
      dockerfile: Dockerfile-java
    depends_on:
      - db
    ports:
      - "8080:8080"
      
  vuejs-app:
    build:
      context: .
      dockerfile: Dockerfile-vue
    ports:
      - "8081:8081"
    depends_on:
      - db
      - javams
      



      
      
      
  

  
