FROM node:18-alpine as build-stage
WORKDIR /app
COPY vue/package*.json ./
RUN npm install
COPY vue .
RUN npm run build
#EXPOSE 3000
#CMD ["npm", "run", "serve", "--", "--port", "3000"]

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
