### STAGE 1: Build ###
FROM node:16-alpine AS builder
WORKDIR /DockerVueApp
COPY ./vue/package*.json ./
RUN npm i
COPY . .
RUN npm install --save-dev @vue/cli-plugin-typescript
RUN echo '{"compilerOptions": {"target": "esnext","module": "esnext","strict": true,"jsx": "preserve","importHelpers": true,"moduleResolution": "node","skipLibCheck": true,"esModuleInterop": true,"allowSyntheticDefaultImports": true,"sourceMap": true,"baseUrl": ".","types": ["webpack-env"],"paths": {"@/*": ["src/*"]},"lib": ["esnext","dom","dom.iterable","scripthost"]}}' > tsconfig.json
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.19.1-alpine
### COPY nginx.conf /etc/nginx/nginx.conf
COPY  --from=builder /DockerVueApp/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
